version: '3'

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - minecraft_world:/minecraft/world
      - minecraft_logs:/minecraft/logs
      - minecraft_backups:/minecraft/backups
    restart: unless-stopped

volumes:
  minecraft_world:
    name: minecraft_world
  minecraft_logs:
    name: minecraft_logs  
  minecraft_backups:
    name: minecraft_backups