version: '3'

services:
  minecraft:
    build:
      context: .
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    volumes:
      - /data/minecraft/:/minecraft
    restart: no
    user: "0:0"
    tty: true
    stdin_open: true