version: '3'

services:
  minecraft:
    build:
      context: .
    ports:
      - "25565:25565"
    volumes:
      - /data/minecraft/world:/minecraft/world
      - /data/minecraft/logs:/minecraft/logs
      - /data/minecraft/meta:/minecraft/
    restart: unless-stopped