header-footer:
  enabled: true
  footer:
  - '%ping%ms | %memory-used%/%memory-max%mb'
  disable-condition: '%world%=disabledworld'
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld'
scoreboard-teams:
  enabled: false
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:owner,admin,mod,helper,builder,vip,default
  - PLACEHOLDER_A_TO_Z:%player%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  disable-condition: '%world%=disabledworld'
playerlist-objective:
  enabled: false
  value: '%health%'
  fancy-value: ' &c%health%'
  disable-condition: '%world%=disabledworld'
  title: Java Edition is better
  render-type: HEARTS
belowname-objective:
  enabled: true
  disable-condition: '%world%=disabledworld'
  fancy-value-default: NPC
  fancy-value: '&f%health%'
  value: '%health%'
  title: '&4❤'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: false
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: '%animation:barcolors%'
      progress: '100'
      text: '&fWebsite: &bwww.domain.com'
scoreboard:
  enabled: false
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: true
  static-number: 0
  delay-on-join-milliseconds: 0
  scoreboards:
    scoreboard-1.20.3+:
      title: <#E0B11E>MyServer</#FF0000>
      display-condition: '%player-version-id%>=765;%bedrock%=false'
      lines:
      - '&7%date%'
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7:||%online%'
      - '* &eCurrent World&7:||%worldonline%'
      - '* &eStaff&7:||%staffonline%'
      - ''
      - '&6Personal Info:'
      - '* &bRank&7:||%group%'
      - '* &bPing&7:||%ping%&8ms'
      - '* &bWorld&7:||%world%'
      - '%animation:MyAnimation1%'
    scoreboard:
      title: <#E0B11E>MyServer</#FF0000>
      lines:
      - '&7%date%'
      - '%animation:MyAnimation1%'
      - '&6Online:'
      - '* &eOnline&7: &f%online%'
      - '* &eCurrent World&7: &f%worldonline%'
      - '* &eStaff&7: &f%staffonline%'
      - ''
      - '&6Personal Info:'
      - '* &bRank&7: &f%group%'
      - '* &bPing&7: &f%ping%&8ms'
      - '* &bWorld&7: &f%world%'
      - '%animation:MyAnimation1%'
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
ping-spoof:
  enabled: false
  value: 0
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  register-tab-expansion: false
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
conditions:
  nick:
    conditions:
    - '%player%=%essentials_nickname%'
    true: '%player%'
    false: ~%essentials_nickname%
assign-groups-by-permissions: false
permission-refresh-interval: 10000
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
  useSSL: true
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
  update-latency: false
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
primary-group-finding-list:
- Owner
- Admin
- Helper
- default
proxy-support:
  enabled: true
  type: PLUGIN
  plugin:
    name: RedisBungee
compensate-for-packetevents-bug: false
placeholder-refresh-intervals:
  default-refresh-interval: 5000
